import {
  Project_Horecah,
  Project_Natour,
  Project_Nexter,
  Project_OldPortfolio,
  Project_Smartle,
  Project_Trello,
} from "@/app/_assets";

export const PROJECTS = [
  {
    id: 1,
    name: "Horecah",
    description:
      "Horecah Hospitality helps people in the hospitality industry hire, find jobs, and the suppliers.",
    tech: ["react", "next", "node", "nest", "aws"],
    git: "",
    link: "https://client.horecah.com",
    year: "",
    image: Project_Horecah,
  },
  {
    id: 2,
    name: "Smartle",
    description: "Fun, social, and safe learning experiences for ages 8 to 14",
    tech: ["react", "node", "aws"],
    git: "",
    link: "https://www.dev.smartle.co/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 3,
    name: "Nexter",
    description: "Luxury Homes Website",
    tech: ["HTML", "CSS"],
    git: "https://github.com/rbaliwal00/nexter",
    link: "https://nexter-grid-demo.netlify.app/",
    year: "",
    image: Project_Nexter,
  },
  {
    id: 4,
    name: "Trillo",
    description: "Hotel Las Palmas Website",
    tech: ["HTML", "CSS"],
    git: "https://github.com/rbaliwal00/trillo-css-flexbox",
    link: "https://trillo-rajan.netlify.app/",
    year: "",
    image: Project_Trello,
  },
  {
    id: 5,
    name: "Natour",
    description: "Exciting tours for adventurous people",
    tech: ["HTML", "CSS"],
    git: "https://github.com/rbaliwal00/natour-scss",
    link: "https://euphonious-sprinkles-93032d.netlify.app/",
    year: "",
    image: Project_Natour,
  },
  {
    id: 6,
    name: "Old Portfolio",
    description: "Old Porfolio website built using gatsby",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/gatsbywebsite",
    link: "https://rajanbaliwal.netlify.app/",
    year: "",
    image: Project_OldPortfolio,
  },
  {
    id: 7,
    name: "Issue Tracker",
    description: "Tracking issues in community made easy",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/gatsbywebsite",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 8,
    name: "Attendance Management",
    description: "Attenence Maganement System for College",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/gatsbywebsite",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 9,
    name: "Task Planner",
    description: "Attenence Maganement System for College",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/gatsbywebsite",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 10,
    name: "List It",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/List-it",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 11,
    name: "List It",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 12,
    name: "Spring Pet Clinic",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 13,
    name: "Recipe Application",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 14,
    name: "Adopt Me",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 15,
    name: "Ticketing",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
  {
    id: 16,
    name: "Electric Bill Optimizer",
    description: "An advertisement web application",
    tech: ["react", "gatsby"],
    git: "https://github.com/rbaliwal00/vehicle-crud-frontend",
    link: "https://vehicle-crud-frontend.vercel.app/",
    year: "",
    image: Project_Smartle,
  },
];
