export const PROJECTS = [
  {
    id: 1,
    name: "Horecah",
    description: "Horecah",
    tech: ["react", "next", "node", "nest", "aws"],
    git: "",
    link: "https://client.horecah.com",
    year: "",
    image: "",
  },
  {
    id: 1,
    name: "Smartle",
    description: "Project 1 description",
    tech: ["react", "node", "aws"],
    git: "",
    link: "https://www.dev.smartle.co/",
    year: "",
    image: "",
  },
  {
    id: 1,
    name: "Project 1",
    description: "Project 1 description",
    tech: [],
    git: "",
    link: "",
    year: "",
    image: "",
  },
  {
    id: 1,
    name: "Project 1",
    description: "Project 1 description",
    tech: [],
    git: "",
    link: "",
    year: "",
    image: "",
  },
  {
    id: 1,
    name: "Project 1",
    description: "Project 1 description",
    tech: [],
    git: "",
    link: "",
    year: "",
    image: "",
  },
  {
    id: 1,
    name: "Project 1",
    description: "Project 1 description",
    tech: [],
    git: "",
    link: "",
    year: "",
    image: "",
  },
];
